name: GitHub-Profile-3D-Contribution

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email uapathrabe@gmail.com
          git add -A .
          git commit -m "GitHub 3D Profile"
          git push